postgres:
  image: postgres:9.3
  restart: always
  ports:
    - 5432
  volumes:
    - ./volumes/postgres/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=postgres
rabbitmq:
  image: rabbitmq:3.6-management
  restart: always
  ports:
    - 5672
    - 15672
  hostname: rabbitmq
php:
  image: lightster/hodor-dev-php:5.6.24.0
  volumes:
    - ./volumes/hodor/:/hodor
  links:
    - postgres
    - rabbitmq
